title: 教务处主动服务规范
aiIgnore: true
icon: rule
cite:
  - https://jwc.nenu.edu.cn/info/2540/5894.htm
time: 2025-07-23T09:43:28.363Z
shareable: true
content:
  - tag: p
    text: |-
      对于到教务处咨询、办事、来访的人员，教务处工作人员要主动服务。教务处第一个看到来访者或被问讯的工作人员，有责任主动为他们办理或引导办理事务。具体要求为:

  - tag: ol
    text:
      - 在教务处区域看到来访人员，要主动询问来访者的意图，并协助来访者办理相关事务；
      - 来访人员进入相关业务办公室区域的，办公室人员要主动接待，严禁对来访人员不理不睬，被动等待询问；
      - 要热情接待，态度和蔼，语言规范，不与来访者发生冲突；
      - 认真听取来访意图，杜绝托辞推诿；
      - 对于自己工作范畴的问题，必须给予认真解答或办理，并对解答的问题负责；
      - 对于处内其它岗位工作范畴的问题，必须引领和介绍来访者到相关岗位；
      - 对于其它部处工作范畴的问题，必须给予引导或指引。
