main-page:
  guest: guest
  "2025": newcomer
  default: at-school

main-presets:
  guest:
    # - tag: list
    #   items:
    #     - text: 登录开启海量校园功能
    #       url: account-login

    - activate-card
    - qq-group-card
    # - under-enroll
    - enroll-basic-info
    - faq-card

  newcomer:
    - tag: functional-list
      header: 如果你觉得 weNENU 对你有帮助，欢迎分享！
      items:
        - text: 向你的同学们分享小程序
          icon: share
          type: button
          openType: share

    - school-basic-info

  at-school:
    - common

intro-page:
  guest:
    items:
      - under-enroll
      - grad-enroll
      - about
      - school
    more:
      - apartment

  default:
    items:
      - about
      - school
      - apartment
    more:
      - under-enroll
      - grad-enroll

guide-page:
  guest:
    items:
      - newcomer
      - life
      - study
      - enjoy
      - normal
    more:
      - account
      - service
      - tip
      - graduate

  "2024":
    items:
      - newcomer
      - life
      - study
      - normal
      - enjoy
      - service
      - account
      - tip
    more:
      - graduate

  "2021":
    items:
      - graduate
      - study
      - service
      - account
    more:
      - life
      - tip
      - enjoy
      - newcomer

  default:
    items:
      - service
      - study
      - life
      - account
    more:
      - normal
      - tip
      - enjoy
      - newcomer
      - graduate

function-page:
  guest: guest
  default: at-school

function-presets:
  guest:
    - account
    - media
    - official
    - info
    - tool
    - under-enroll
    - grad-enroll

  at-school:
    - action
    - under-study
    - media
    - official
    - info
    - tool
    - under-enroll
    - grad-enroll

user:
  - tag: list
    items:
      - text: 使用指南
        icon: idea
        url: info?path=Oguide/

      - text: 更新日志
        icon: log
        url: info?path=Olog/

      - text: 隐私说明
        icon: privacy
        url: privacy

      - text: 关于
        icon: about
        url: about

  - tag: p
    header: " "
    text:
      - 如果看过小程序后您还有疑问，欢迎加入 inNENU 咨询群 (1139044856) 进行咨询。
      - 小程序为 Mr.Hope 个人独自开发编写，现已花费 Mr.Hope 超 3300 小时，文字数量超过 106 万字，同时小程序服务器每年会产生开销。如果您觉得小程序很有帮助，欢迎您给予支持。
    style: "color: #888; font-size: 14px"

  - tag: functional-list
    items:
      - text: 分享小程序
        icon: share
        type: button
        openType: share

      - text: inNENU 微信公众号
        icon: wechat
        url: qrcode

      - text: inNENU 微信视频号
        icon: wechat
        type: button
        handler: openChannel

      - text: 联系 Mr.Hope
        icon: contact
        type: button
        openType: contact
        handler: reportInfo

about:
  - tag: list
    header: 小程序介绍
    items:
      - text: 小程序全部内容均由 Mr.Hope 独立开发。

      - text: 小程序现有字数为 1060769 字，其中东师指南部分 316768 字，新生迎新部分 98607 字，东师介绍部分 238295 字，机构介绍部分 57210 字，学院介绍部分 158529 字，功能大厅部分 38717 字，其他部分 152643 字。

      - text: Mr.Hope 个人介绍
        url: info?path=Oabout/mrhope

      - text: |-
          记: weNENU
        url: info?path=Oabout/history

      - text: 开发者访谈
        url: info?path=Oabout/interview

      - text: 常见问题
        url: info?path=Oabout/function

      - text: 致谢名单
        url: info?path=Oabout/thanks

  - tag: functional-list
    header: 支持小程序
    items:
      - text: 为保证小程序运行，每年购买维护服务器资源会产生开销。如果您希望帮助 Mr.Hope，欢迎联系 Mr.Hope 施以援手。

      - text: 联系 Mr.Hope
        icon: contact
        type: button
        openType: contact
        handler: reportInfo

  - tag: text
    header: 小程序内容
    text:
      - 小程序页面内容仓库在 GitHub 上开源。如您愿意对小程序提供帮助，欢迎您点击下方链接为该仓库做贡献。您可以帮助扩充或编辑小程序的页面文字、图片以及相关文件。

  - tag: action
    content: https://github.com/inNENU/resource

  - tag: list
    header: 内容版权及使用
    items:
      - text: 请您特别注意，除标注来源的文字、图片 Mr.Hope 没有版权外，其余文字、图片均放置在『CC BY-NC-ND 4.0』协议下。请您合法使用这些文字与图片，以避免引起纠纷。

      - text: 协议详情
        url: info?path=Oabout/copyright

service:
  # 新版统一身份登录存在 Referrer 问题
  auth-init-info: online
  auth-init: online
  auth-login: online
  auth-captcha: online
  re-auth: online
  action-login: online
  auth-center-login: online
  my-login: online
  under-study-login: online
  under-system-login: online
  # 本科教务系统全部存在 Referrer 问题
  under-study-check: online
  under-course-table: online
  under-commentary: online
  under-grade-detail: online
  under-grade-list: online
  under-special-exam: online
  under-select-category: online
  under-select-class: online
  under-select-info: online
  under-select-process: online
  under-select-search: online
  under-select-selected: online

notice:
  main:
    title: 欢迎使用 weNENU
    content: 欢迎使用 weNENU。这是一个由 Mr.Hope 个人制作的非官方小程序，内含 106 万字的新生攻略。希望大家能够通过小程序摆脱对大学的迷茫。

  account-login:
    title: 异地登录提示
    content: 为了通过统一身份认证系统，小程序需要通过服务器转发登录请求解析登录令牌后以小程序可以理解的方式返回。由于小程序服务器位于北京，这一过程会出现异地登录提示。请放心，这并不会影响您的账号安全。

  account-activate:
    title: 提示
    content: 目前 2025 级新生已经可以进行账号激活了。如遇到问题，请联系 0431-85099005
    force: true

update:
  force: true
  reset: false
