main-page:
  default: default

main-presets:
  default:
    - tag: grid
      header: 您可能想关注
      items:
        - text: 寝室
          icon: dorm
          path: guide/dorm/

        - text: 食堂
          icon: dining
          path: guide/dining/

        - text: 快递
          icon: express
          path: guide/express/

        - text: 校园卡
          icon: card
          path: guide/card/

intro-page:
  default:
    items:
      - about-fake
    more: []

guide-page:
  default:
    items:
      - guide-fake
      - enjoy
      - tip
    more: []

function-page:
  guest: guest
  default: at-school

function-presets:
  guest:
    - account

    - tag: grid
      header: 东师风采
      items:
        - text: 校园地图
          icon: map
          url: map

    - tool

    - tag: list
      items:
        - text: 登录开启海量校园功能
          url: account-login
      footer: " "

  at-school:
    - action
    - under-study

    - tag: grid
      header: 东师风采
      items:
        - text: 校园地图
          icon: map
          url: map

    - tag: grid
      header: 信息查询
      items:
        - text: 校历
          icon: calendar
          url: calendar

        - text: 东师网站
          icon: network
          url: website

        - text: 师大黄页
          icon: phone
          url: phone

    - tool

user:
  - tag: list
    items:
      - text: 使用指南
        icon: idea
        url: info?path=Oapp-intro/

      - text: 更新日志
        icon: log
        url: info?path=Olog/

      - text: 隐私说明
        icon: privacy
        url: privacy

      - text: 关于
        icon: about
        url: about

  - tag: p
    header: " "
    text:
      - 如果看过小程序后您还有疑问，欢迎加入 inNENU 咨询群 (1139044856) 进行咨询。
      - 小程序为 Mr.Hope 个人独自开发编写，现已花费 Mr.Hope 超 3300 小时，文字数量超过 106 万字。
    style: "color: #888; font-size: 14px"

  - tag: functional-list
    items:
      - text: 分享小程序
        icon: share
        type: button
        openType: share

      - text: 联系 Mr.Hope
        icon: contact
        type: button
        openType: contact
        handler: reportInfo

about:
  - tag: list
    header: 小程序介绍
    items:
      - text: 小程序全部内容均由 Mr.Hope 独立开发。

      - text: 小程序现有字数为 1062421 字，其中东师指南部分 316839 字，新生迎新部分 99497 字，东师介绍部分 238341 字，机构介绍部分 57210 字，学院介绍部分 158529 字，功能大厅部分 39197 字，其他部分 152808 字。

      - text: Mr.Hope 个人介绍
        url: info?path=Oabout/mrhope

      - text: |-
          记: inNENU
        url: info?path=Oabout/history

      - text: 开发者访谈
        url: info?path=Oabout/interview

      - text: 致谢名单
        url: info?path=Oabout/thanks

      - text: 更多详情
        url: info?path=Oapp-intro/

  - tag: text
    header: 小程序内容
    text:
      - 小程序页面内容仓库在 GitHub 上开源。如您愿意对小程序提供帮助，欢迎您点击下方链接为该仓库做贡献。您可以帮助扩充或编辑小程序的页面文字、图片以及相关文件。

  - tag: action
    content: https://github.com/inNENU/resource

  - tag: list
    header: 内容版权及使用
    items:
      - text: 请您特别注意，除标注来源的文字、图片 Mr.Hope 没有版权外，其余文字、图片均放置在『CC BY-NC-ND 4.0』协议下。请您合法使用这些文字与图片，以避免引起纠纷。

      - text: 协议详情
        url: info?path=Oabout/copyright

service:
  forceOnline: true

notice:
  main:
    title: 欢迎使用 inNENU
    content: 欢迎使用 inNENU。这是一个由 Mr.Hope 个人制作的非官方小程序，内含 106 万字的新生攻略。希望大家能够通过小程序摆脱对大学的迷茫。

  account-activate:
    title: 提示
    content: 2025 级新生目前可激活账号。如激活中遇到问题，请联系信息化办公室 0431-85099005。
    force: true

update:
  force: true
  reset: false
