main-page:
  guest: guest
  "2025": newcomer
  default: at-school

main-presets:
  guest:
    - tag: list
      items:
        - text: 登录开启海量校园功能
          url: account-login

    - under-enroll
    - enroll-basic-info

  newcomer:
    - tag: functional-list
      header: 如果你觉得 weNENU 对你有帮助，欢迎分享！
      items:
        - text: 向你的同学们分享小程序
          icon: share
          type: button
          openType: share

    - school-basic-info

  at-school:
    - common

intro-page:
  guest:
    items:
      - under-enroll
      - grad-enroll
      - about
      - school
    more:
      - apartment

  default:
    items:
      - about
      - school
      - apartment
    more:
      - under-enroll
      - grad-enroll

guide-page:
  guest:
    items:
      - newcomer
      - life
      - study
      - enjoy
      - normal
    more:
      - account
      - service
      - tip
      - graduate

  "2024":
    items:
      - newcomer
      - life
      - study
      - normal
      - enjoy
      - service
      - account
      - tip
    more:
      - graduate

  "2021":
    items:
      - graduate
      - study
      - service
      - account
    more:
      - life
      - tip
      - enjoy
      - newcomer

  default:
    items:
      - service
      - study
      - life
      - account
    more:
      - normal
      - tip
      - enjoy
      - newcomer
      - graduate

function-page:
  guest: guest
  default: at-school

function-presets:
  guest:
    - account
    - media
    - official
    - info
    - tool
    - under-enroll
    - grad-enroll

  at-school:
    - action
    - under-study
    - media
    - official
    - info

    - tag: grid
      header: 账号相关
      items:
        - text: 账号激活
          icon: authorize
          url: account-activate

        - text: 校园邮箱邮件
          icon: email
          url: email-recent

        - text: 校外服务
          icon: contact
          url: info?path=/other/action/out

        # - text: 密码重置
        #   icon: reset
        #   url: account-reset

        # - text: 邮箱申请
        #   icon: email
        #   url: email-apply

    - tag: grid
      header: 管理系统
      items:
        - text: 统一身份认证
          icon: account
          url: web?url=https://authserver.nenu.edu.cn/authserver/login

        - text: 网上服务大厅
          icon: network
          url: web?url=https://oa.nenu.edu.cn/

        - text: 故障报修
          icon: repair
          url: web?url=https://gyglxt.nenu.edu.cn/repair/redirect/website/index

        - text: 宿舍系统
          icon: system
          url: web?url=https://gyglxt.nenu.edu.cn/?sid=https://gyglxt.nenu.edu.cn

    - tool
    - under-enroll
    - grad-enroll

user:
  - tag: list
    items:
      - text: 使用指南
        icon: idea
        url: info?path=Oguide/

      - text: 更新日志
        icon: log
        url: info?path=Olog/

      - text: 隐私说明
        icon: privacy
        url: privacy

      - text: 关于
        icon: about
        url: about

  - tag: p
    header: " "
    text:
      - 如果看过 App 后您还有疑问，欢迎加入 inNENU 咨询群 (1139044856) 进行咨询。
      - App 为 Mr.Hope 个人独自开发编写，现已花费 Mr.Hope 超 3300 小时，文字数量超过 106 万字，同时 App 服务器每年会产生开销。如果您觉得 App 很有帮助，欢迎您给予支持。
    style: "color: #888; font-size: 14px"

about:
  - tag: list
    header: App 介绍
    items:
      - text: App 全部内容均由 Mr.Hope 独立开发。

      - text: App 现有字数为 1060698 字，其中东师指南部分 316768 字，新生迎新部分 98607 字，东师介绍部分 238295 字，机构介绍部分 57210 字，学院介绍部分 158529 字，功能大厅部分 38646 字，其他部分 152643 字。

      - text: Mr.Hope 个人介绍
        url: info?path=Oabout/mrhope

      - text: |-
          记: inNENU
        url: info?path=Oabout/history

      - text: 开发者访谈
        url: info?path=Oabout/interview

      - text: 常见问题
        url: info?path=Oabout/function

      - text: 致谢名单
        url: info?path=Oabout/thanks

  - tag: functional-list
    header: 支持 App
    items:
      - text: 为保证 App 运行，每年购买维护服务器资源会产生开销。如果您希望帮助 Mr.Hope，欢迎联系 Mr.Hope 施以援手。

      - text: 联系 Mr.Hope
        icon: contact
        type: button
        openType: contact
        handler: reportInfo

  - tag: text
    header: App 内容
    text:
      - App 页面内容仓库在 GitHub 上开源。如您愿意对 App 提供帮助，欢迎您点击下方链接为该仓库做贡献。您可以帮助扩充或编辑 App 的页面文字、图片以及相关文件。

  - tag: action
    content: https://github.com/inNENU/resource

  - tag: list
    header: 内容版权及使用
    items:
      - text: 请您特别注意，除标注来源的文字、图片 Mr.Hope 没有版权外，其余文字、图片均放置在『CC BY-NC-ND 4.0』协议下。请您合法使用这些文字与图片，以避免引起纠纷。

      - text: 协议详情
        url: info?path=Oabout/copyright

service:
  # 新版统一身份登录存在 Referrer 问题
  auth-init-info: online
  auth-init: online
  auth-login: online
  auth-captcha: online
  re-auth: online
  action-login: online
  auth-center-login: online
  my-login: online
  under-study-login: online
  under-system-login: online
  # 本科教务系统全部存在 Referrer 问题
  under-study-check: online
  under-course-table: online
  under-commentary: online
  under-grade-detail: online
  under-grade-list: online
  under-special-exam: online
  under-select-category: online
  under-select-class: online
  under-select-info: online
  under-select-process: online
  under-select-search: online
  under-select-selected: online

notice:
  main:
    title: 欢迎使用 inNENU
    content: 欢迎使用 inNENU。这是一个由 Mr.Hope 个人制作的非官方 App，内含 106 万字的新生攻略。希望大家能够通过 App 摆脱对大学的迷茫。

  account-login:
    title: 异地登录提示
    content: 为了通过统一身份认证系统，小程序需要通过服务器转发登录请求解析登录令牌后以小程序可以理解的方式返回。由于小程序服务器位于北京，这一过程会出现异地登录提示。请放心，这并不会影响您的账号安全。

  account-activate:
    title: 提示
    content: 2025级新生账户尚未启用，研究生新生目前无法激活账户。
    # content: 如果你认为你输入了正确的信息但无法激活，请联系我校信息化办公室，电话 0431-85099005。
    force: true

update:
  force: true
  reset: false
