activate-card:
  tag: card
  cover: $img/tab/activate.jpg
  title: 账号激活
  url: account-activate

activate-hint:
  tag: text
  type: info
  header: 点击激活学校账号（未激活）
  url: account-activate

login-hint:
  tag: text
  type: info
  header: 点击登录学校账号（已激活）
  url: account-login

admission-card:
  tag: card
  cover: $img/tab/admission.jpg
  title: 录取查询
  url: admission?type=search

qq-group-card:
  tag: card
  cover: $img/tab/qq-group.jpg
  title: 快来加入新生群
  path: newcomer/contact/all

qq-group-hint:
  tag: text
  type: info
  header: 加入新生群
  path: newcomer/contact/all

faq-card:
  tag: card
  cover: $img/tab/faq.png
  title: 常见问题
  path: newcomer/faq/

stream-card:
  tag: card
  cover: $img/tab/stream.png
  title: 经验分享与答疑 (非常有用)
  desc: 直播分享已结束，可看回放
  path: newcomer/activity/streaming

yiban-card:
  tag: card
  cover: $img/tab/yiban.jpg
  title: 新生入学教育现已开放
  path: newcomer/yiban/

check:
  tag: grid
  header: 报到相关
  items:
    - text: 到校路线
      icon: locate
      path: newcomer/arrival/

    - text: 校园导航
      icon: map
      url: map

    - text: 新生报到
      icon: check
      path: newcomer/check/

    - text: 物品清单
      icon: necessity
      path: newcomer/necessity/

    - text: 入学活动
      icon: activity
      path: newcomer/activity/

    - text: 军训
      icon: military
      path: newcomer/activity/military/

    - text: 新生群
      icon: qq-group
      path: newcomer/contact/

    - text: 防盗防骗
      icon: safe
      path: newcomer/safety/

enroll-basic-info:
  tag: grid
  header: 您可能想关注
  items:
    - text: 常见问题
      icon: faq
      path: newcomer/faq/

    - text: 寝室
      icon: dorm
      path: guide/dorm/

    - text: 食堂
      icon: dining
      path: guide/dining/

    - text: 洗浴
      icon: bath
      path: guide/bath/

    - text: 生活
      icon: life
      path: guide/life/

    - text: 课程
      icon: content
      path: guide/course/

    - text: 学习
      icon: study
      path: guide/study/

    - text: 奖学金
      icon: metal
      path: intro/scholarship/

    - text: 转专业
      icon: change
      path: guide/change-major/

    - text: 师范生
      icon: teacher
      path: guide/normal/

    - text: 校园媒体
      icon: account
      url: school-media

  footer: 更多详情请访问下方东师介绍与东师指南查看

school-basic-info:
  tag: grid
  header: 您可能想关注
  items:
    - text: 寝室
      icon: dorm
      path: guide/dorm/

    - text: 食堂
      icon: dining
      path: guide/dining/

    - text: 快递
      icon: express
      path: guide/express/

    - text: 洗浴
      icon: bath
      path: guide/bath/

    - text: 生活
      icon: life
      path: guide/life/

    - text: 校园网
      icon: network
      path: guide/network/

    - text: 校园卡
      icon: card
      path: guide/card/

    - text: 课程
      icon: content
      path: guide/course/

    - text: 学习
      icon: study
      path: guide/study/

    - text: 奖学金
      icon: metal
      path: intro/scholarship/

    - text: 转专业
      icon: change
      path: guide/change-major/

    - text: 师范生
      icon: teacher
      path: guide/normal/

    - text: 校园地图
      icon: map
      url: map

    - text: 校园媒体
      icon: account
      url: school-media

    - text: 学生组织
      icon: student-org
      path: guide/org/

    - text: 社团
      icon: association
      path: guide/association/

  footer: 更多详情请访问下方东师介绍与东师指南查看

common:
  tag: grid
  header: 功能
  items:
    - text: 课程表
      icon: course-table
      url: under-course-table

    - text: 成绩查询
      icon: grade
      url: under-grade

    - text: 学校通知
      icon: notice
      url: notice-list

    - text: 校园邮箱
      icon: email
      url: email-recent

    - text: 校历
      icon: calendar
      url: calendar

  footer: 更多内容请详见下方其他 Tab 页

account:
  tag: grid
  header: 账号
  items:
    - text: 账号激活
      icon: authorize
      url: account-activate

    - text: 账号登录
      icon: account
      url: account-login

action:
  tag: grid
  header: 融合门户
  items:
    - text: 学校通知
      icon: notice
      url: notice-list

    - text: 学校新闻
      icon: news
      url: notice-list?type=news

    - text: 校园邮箱邮件
      icon: email
      url: email-recent

    - text: 图书馆
      icon: library
      url: library

official:
  tag: grid
  header: 学校动态
  items:
    - text: 通知公告
      icon: notice
      url: official-notice-list

    - text: 要闻速递
      icon: news
      url: official-info-list?type=news

    - text: 媒体师大
      icon: media
      url: official-info-list?type=media

    - text: 人文社科
      icon: marx
      url: official-info-list?type=social

    - text: 自然科学
      icon: chemistry
      url: official-info-list?type=science

    - text: 学术预告
      icon: study
      url: official-academic-list

media:
  tag: grid
  header: 东师风采
  items:
    - text: 校园地图
      icon: map
      url: map

    - text: 音悦东师
      icon: cd
      url: music

    - text: 影约东师
      icon: media
      url: video?type=video

    - text: 校园媒体
      icon: account
      url: school-media

info:
  tag: grid
  header: 信息查询
  items:
    - calendar
    - under-major-plan
    - website
    - phone
    - calendar-history

tool:
  tag: grid
  header: 工具
  items:
    - pe-calculator
    - weather

grad-enroll:
  tag: grid
  header: 研究生招生
  items:
    - text: 招生简章
      icon: rule
      path: intro/enroll/grad/rule/

    - text: 招生计划
      icon: enroll
      url: grad-enroll-plan

    - text: 推免计划
      icon: time
      url: grad-enroll-plan?recommend=true

under-enroll:
  tag: grid
  header: 本科招生
  items:
    - admission

    - text: 招生简章
      icon: rule
      path: intro/enroll/under/rule/

    - text: 招生计划
      icon: enroll
      url: under-enroll-plan

    - text: 历史分数
      icon: time
      url: under-enroll-score

first-day:
  tag: card
  cover: $img/tab/first-day.png
  title: 开启你的东师校园生活
  path: newcomer/check/first-day

under-study:
  tag: grid
  header: 本科教务系统
  items:
    - text: 课程表
      icon: course-table
      url: under-course-table

    - text: 成绩查询
      icon: grade
      url: under-grade

    - text: 选课系统
      icon: select
      url: under-select

    - text: 考场查询
      icon: test
      url: exam-place

    - text: 专项考试成绩
      icon: test
      url: grade-special

    # - text: 学籍注册查看
    #   icon: archive
    #   url: under-archive-view

    # - text: 建立学籍
    #   icon: archive
    #   url: under-archive-create

    # - text: 转专业计划
    #   icon: change
    #   url: change-major

    - text: 课程评价
      icon: heart
      url: under-commentary

map:
  tag: card
  cover: $img/tab/map.jpg
  title: 校园地图
  url: map
